import React, { useState, useRef, useEffect } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useAuth } from '../context/AuthContext';
import { Button, Toast } from '../components/ui';
import { 
  Bot, 
  Send, 
  Trash2, 
  RefreshCw, 
  Sparkles, 
  HelpCircle,
  TrendingUp,
  MapPin,
  ClipboardList
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export default function AiAssistant() {
  const { token, user } = useAuth();
  const [messages, setMessages] = useState([
    {
      id: 'welcome',
      role: 'assistant',
      message: `Namaste **${user?.name || 'Grower'}**! 🙏 Welcome to your **HimalayaGrow AI Assistant**.

I am trained specifically to help micro-businesses in the Uttarakhand valleys. Ask me about:
*   **Agriculture & Soil Health:** Crop rotation plans, organic compost, terrace farming.
*   **Government Subsidies:** PM-KISAN enrollment, Apple Mission, food processing grants.
*   **Business Growth & Brand:** Designing local labels, WhatsApp marketing campaigns, tourist outreach.

How can I assist your business today?`
    }
  ]);
  
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [toast, setToast] = useState(null);
  const [lastUserMessage, setLastUserMessage] = useState('');
  const messagesEndRef = useRef(null);

  // Quick starter suggestions
  const starters = [
    {
      label: 'Uttarakhand Crop Rotation',
      icon: <MapPin className="w-3.5 h-3.5" />,
      prompt: 'Suggest a good organic crop rotation plan for my terrace farm in Mussoorie hills.'
    },
    {
      label: 'PM-KISAN Guidelines',
      icon: <ClipboardList className="w-3.5 h-3.5" />,
      prompt: 'What are the eligibility requirements for PM-KISAN and how do I apply in Uttarakhand?'
    },
    {
      label: 'Apple Mission Subsidy',
      icon: <TrendingUp className="w-3.5 h-3.5" />,
      prompt: 'Tell me about the Uttarakhand Apple Mission scheme and orchard setting subsidies.'
    },
    {
      label: 'Brand Apple Jams',
      icon: <Sparkles className="w-3.5 h-3.5" />,
      prompt: `Create a marketing and packaging idea for our organic apple jams from "${user?.shopName || 'our family farm'}".`
    }
  ];

  const showToast = (message, type = 'info') => {
    setToast({ message, type });
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading]);

  const handleSendMessage = async (textToSend) => {
    const query = textToSend || input;
    if (!query.trim()) return;

    // Save message and reset input
    const userMsgId = `user-${Date.now()}`;
    const newMessages = [
      ...messages,
      { id: userMsgId, role: 'user', message: query }
    ];
    setMessages(newMessages);
    if (!textToSend) setInput('');
    setLastUserMessage(query);
    setLoading(true);

    try {
      // Format chat history for Gemini API
      // Backend expects: [{ role: 'user' | 'model', message: '...' }]
      const chatHistory = messages
        .filter(m => m.id !== 'welcome')
        .map(m => ({
          role: m.role,
          message: m.message
        }));

      const res = await fetch('http://localhost:5000/api/ai/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          message: query,
          history: chatHistory
        })
      });

      const data = await res.json();
      setLoading(false);

      if (data.success) {
        setMessages(prev => [
          ...prev,
          { id: `ai-${Date.now()}`, role: 'assistant', message: data.replyText }
        ]);
        if (data.source.includes('fallback') || data.source.includes('simulator')) {
          showToast('Running in local offline simulator mode.', 'info');
        } else {
          showToast('Response generated by Gemini AI.', 'success');
        }
      } else {
        showToast(data.message || 'Failed to generate response.', 'error');
        // Add retry indicator to message list
        setMessages(prev => [
          ...prev,
          { id: `err-${Date.now()}`, role: 'error', message: 'Failed to connect to AI server. Please try again.' }
        ]);
      }

    } catch (err) {
      setLoading(false);
      showToast('Could not connect to AI services. Check network connection.', 'error');
      setMessages(prev => [
        ...prev,
        { id: `err-${Date.now()}`, role: 'error', message: 'Network connection failed. Click Retry below to re-submit.' }
      ]);
    }
  };

  const handleRetry = () => {
    // Remove last error message if any
    setMessages(prev => prev.filter(m => m.role !== 'error'));
    if (lastUserMessage) {
      handleSendMessage(lastUserMessage);
    }
  };

  const handleClearChat = () => {
    setMessages([
      {
        id: 'welcome',
        role: 'assistant',
        message: `Namaste **${user?.name || 'Grower'}**! 🙏 Conversation cleared. How can I help you grow your business today?`
      }
    ]);
    showToast('Conversation logs cleared.', 'info');
  };

  // Safe renderer for markdown bullet points and headings
  const renderMessageContent = (text) => {
    return text.split('\n').map((line, idx) => {
      let content = line;
      let className = "text-xs sm:text-sm leading-relaxed";

      // Bold text handling: **text**
      const boldRegex = /\*\*(.*?)\*\*/g;
      const parts = [];
      let lastIndex = 0;
      let match;
      while ((match = boldRegex.exec(content)) !== null) {
        if (match.index > lastIndex) {
          parts.push(content.substring(lastIndex, match.index));
        }
        parts.push(<strong key={match.index} className="font-extrabold text-forest-900 dark:text-clay-100">{match[1]}</strong>);
        lastIndex = boldRegex.lastIndex;
      }
      if (lastIndex < content.length) {
        parts.push(content.substring(lastIndex));
      }
      
      const parsedText = parts.length > 0 ? parts : content;

      if (line.startsWith('### ')) {
        return <h4 key={idx} className="text-xs sm:text-sm font-bold uppercase tracking-wider text-sage-600 dark:text-sage-400 mt-3 mb-1">{line.replace('### ', '')}</h4>;
      }
      if (line.startsWith('## ')) {
        return <h3 key={idx} className="text-sm sm:text-base font-bold text-forest-900 dark:text-clay-50 mt-4 mb-2">{line.replace('## ', '')}</h3>;
      }
      if (line.startsWith('*   ') || line.startsWith('-   ')) {
        return (
          <li key={idx} className="ml-4 list-disc text-xs sm:text-sm leading-relaxed py-0.5">
            {line.substring(4)}
          </li>
        );
      }
      if (line.startsWith('* ') || line.startsWith('- ')) {
        return (
          <li key={idx} className="ml-4 list-disc text-xs sm:text-sm leading-relaxed py-0.5">
            {line.substring(2)}
          </li>
        );
      }
      if (/^\d+\.\s/.test(line)) {
        return (
          <li key={idx} className="ml-4 list-decimal text-xs sm:text-sm leading-relaxed py-0.5">
            {line.replace(/^\d+\.\s/, '')}
          </li>
        );
      }
      if (line.trim() === '') {
        return <div key={idx} className="h-2" />;
      }

      return <p key={idx} className={className}>{parsedText}</p>;
    });
  };

  return (
    <div className="bg-clay-50 dark:bg-forest-950 text-forest-900 dark:text-clay-50 min-h-screen flex flex-col justify-between transition-colors duration-500 relative overflow-hidden">
      
      {/* Background glowing blobs */}
      <div className="absolute top-20 left-10 w-96 h-96 bg-sage-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-20 right-10 w-96 h-96 bg-sage-500/5 rounded-full blur-3xl pointer-events-none" />

      {/* Toast panel */}
      <AnimatePresence>
        {toast && (
          <motion.div 
            initial={{ opacity: 0, y: 50, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            className="fixed bottom-6 right-6 z-55 max-w-sm w-full pointer-events-auto"
          >
            <Toast 
              message={toast.message} 
              type={toast.type} 
              onClose={() => setToast(null)} 
            />
          </motion.div>
        )}
      </AnimatePresence>

      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 py-8 flex flex-col space-y-6 relative z-10">
        
        {/* Page Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-slate-200/50 dark:border-slate-800/40 pb-6">
          <div>
            <span className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-sage-500/10 text-sage-600 dark:text-sage-400 text-[9px] uppercase font-black tracking-widest">
              <span>Himalayan AI Helper</span>
            </span>
            <h1 className="text-2xl sm:text-3xl font-bold font-display tracking-tight mt-2 flex items-center space-x-2">
              <Bot className="w-7 h-7 text-sage-500" />
              <span>HimalayaGrow AI Assistant</span>
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1 font-medium">
              Consult our AI on agricultural advice, government schemes, and marketing content templates.
            </p>
          </div>
          
          <button
            onClick={handleClearChat}
            className="flex items-center space-x-2 px-3 py-1.5 border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#19221F] rounded-xl hover:bg-slate-50 dark:hover:bg-forest-900/60 transition-all text-xs font-semibold cursor-pointer text-forest-900 dark:text-clay-50"
            title="Clear Chat Logs"
          >
            <Trash2 className="w-3.5 h-3.5 text-rose-500" />
            <span>Clear Chat</span>
          </button>
        </div>

        {/* Quick Prompts Panel */}
        <div className="space-y-2">
          <span className="text-[10px] uppercase font-bold text-slate-450 dark:text-slate-500 tracking-wider flex items-center space-x-1">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Suggested Starter Queries</span>
          </span>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {starters.map((item, idx) => (
              <button
                key={idx}
                onClick={() => handleSendMessage(item.prompt)}
                disabled={loading}
                className="flex items-center space-x-3 p-3 text-left border border-slate-200/50 dark:border-slate-800/40 bg-white/60 dark:bg-[#19221F]/60 backdrop-blur-md rounded-2xl hover:border-sage-500 dark:hover:border-sage-600 hover:scale-[1.01] transition-all duration-300 cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
              >
                <div className="p-2 bg-sage-500/10 rounded-xl text-sage-600 dark:text-sage-400">
                  {item.icon}
                </div>
                <div className="space-y-0.5">
                  <p className="text-[11px] font-bold text-forest-900 dark:text-clay-50 leading-snug">{item.label}</p>
                  <p className="text-[9px] text-slate-450 dark:text-slate-500 truncate max-w-[280px]">{item.prompt}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Chat Logs Window */}
        <div className="flex-1 bg-white dark:bg-[#19221F] border border-slate-200/50 dark:border-slate-800/40 rounded-3xl p-4 sm:p-6 shadow-xs flex flex-col h-[420px] overflow-hidden">
          
          <div className="flex-1 overflow-y-auto pr-2 space-y-4">
            {messages.map((m) => {
              if (m.role === 'error') {
                return (
                  <div key={m.id} className="flex justify-center my-4">
                    <div className="bg-rose-50 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-900/40 rounded-2xl p-4 max-w-md text-center space-y-3">
                      <p className="text-xs font-semibold text-rose-600 dark:text-rose-400">{m.message}</p>
                      <Button 
                        variant="danger" 
                        size="sm" 
                        onClick={handleRetry} 
                        className="text-[10px] font-bold uppercase tracking-wider py-1.5 px-3 mx-auto cursor-pointer"
                        icon={<RefreshCw className="w-3.5 h-3.5 mr-1" />}
                      >
                        Retry Send
                      </Button>
                    </div>
                  </div>
                );
              }

              const isUser = m.role === 'user';
              return (
                <div key={m.id} className={`flex ${isUser ? 'justify-end' : 'justify-start'} animate-fade-in-blur`}>
                  <div className={`flex items-start space-x-3.5 max-w-[85%] ${isUser ? 'flex-row-reverse space-x-reverse' : ''}`}>
                    
                    {/* Bubble Avatar icon */}
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center border shrink-0 ${
                      isUser 
                        ? 'bg-forest-900 border-forest-900 text-clay-50' 
                        : 'bg-sage-500/10 border-sage-500/10 text-sage-600'
                    }`}>
                      {isUser ? <span className="text-[11px] font-bold">U</span> : <Bot className="w-4 h-4" />}
                    </div>

                    {/* Content Text bubble */}
                    <div className={`p-4 rounded-3xl text-left border ${
                      isUser
                        ? 'bg-forest-900 border-forest-900 text-clay-50 dark:bg-clay-100 dark:border-clay-100 dark:text-forest-950 rounded-tr-none'
                        : 'bg-slate-50/50 dark:bg-forest-900/40 border-slate-100 dark:border-slate-800/40 text-slate-700 dark:text-slate-350 rounded-tl-none'
                    }`}>
                      <div className="space-y-1">
                        {renderMessageContent(m.message)}
                      </div>
                    </div>

                  </div>
                </div>
              );
            })}

            {/* Skeleton Loading Panel during API query */}
            {loading && (
              <div className="flex justify-start animate-pulse">
                <div className="flex items-start space-x-3.5 max-w-[80%]">
                  <div className="w-8 h-8 rounded-full bg-sage-500/10 flex items-center justify-center shrink-0">
                    <Bot className="w-4 h-4 text-sage-600" />
                  </div>
                  <div className="bg-slate-50/50 dark:bg-forest-900/40 border border-slate-100 dark:border-slate-800/40 p-4 rounded-3xl rounded-tl-none w-64 space-y-2.5">
                    {/* Animated Pulsing Typing dots */}
                    <div className="flex items-center space-x-1.5 py-1">
                      <div className="w-1.5 h-1.5 bg-sage-500 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <div className="w-1.5 h-1.5 bg-sage-500 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <div className="w-1.5 h-1.5 bg-sage-500 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                    {/* Skeletons lines */}
                    <div className="h-2.5 bg-slate-200 dark:bg-slate-700 rounded-full w-full" />
                    <div className="h-2.5 bg-slate-200 dark:bg-slate-700 rounded-full w-5/6" />
                  </div>
                </div>
              </div>
            )}
            
            <div ref={messagesEndRef} />
          </div>

          {/* Form Input panel */}
          <form 
            onSubmit={(e) => { e.preventDefault(); handleSendMessage(); }}
            className="border-t border-slate-100 dark:border-slate-800/60 pt-4 mt-2 flex items-center space-x-3"
          >
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about crop rotation, scheme eligibility, marketing jams..."
              disabled={loading}
              className="flex-1 bg-slate-50 dark:bg-forest-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl py-3 px-4 text-xs font-semibold text-slate-750 dark:text-clay-50 placeholder-slate-400 focus:outline-none focus:border-sage-500 transition-colors disabled:opacity-50"
            />
            <Button
              variant="primary"
              type="submit"
              disabled={loading || !input.trim()}
              className="py-3 px-4 rounded-2xl cursor-pointer bg-forest-900 dark:bg-clay-50 text-clay-50 dark:text-forest-950 transition-all select-none shrink-0"
              icon={<Send className="w-4 h-4" />}
            />
          </form>

        </div>

      </main>

      <Footer />
    </div>
  );
}
